### ISSUE TITLE
Prevent the Blue highlighting of elements on tapping in mobile 

### ISSUE THREAD

**Issue by muhammedanaskhan** [snehafarkya/Translate-Lingo#1]
![Screenshot](https://github.com/snehafarkya/Translate-Lingo/assets/72510634/52927133-e9b0-4789-85ab-f8cd3171b3e1)

Please assign me this to work on, thanks!

**Comment by snehafarkya** [comment]
Sure @muhammedanaskhan You can work on this. Make sure to fork the repo, clone it, and create a new branch.
