### ISSUE TITLE
Navbar UI Improvement

### ISSUE THREAD

**Issue by Jaspreet099** [snehafarkya/Translate-Lingo#12]
The navbar should be in white color it will give good contrast, I have tried this with a drop shadow in inspect element

If you think it will make Nav UI good, please assign this issue to me, I'll update the background and drop shadow 

![image](https://github.com/snehafarkya/Translate-Lingo/assets/75212002/3f4e8773-f065-42b2-ba1c-890adddb68a1)

**Comment by snehafarkya** [comment]
hey @Jaspreet099 , that's a nice idea! You can work on this.
Thankyou
