### ISSUE TITLE
Way to stop speech generation in text to speech

### ISSUE THREAD

**Issue by Saumya40-codes** [snehafarkya/Translate-Lingo#9]
Currently there is no way a speech generation can be stopped in text-to-speech part 

![image](https://github.com/snehafarkya/Translate-Lingo/assets/115284013/11cbd699-378e-49ba-9696-9b1a78600cdd)

thus, for long texts it will be good if it can be stopped. 

Current result:

![image](https://github.com/snehafarkya/Translate-Lingo/assets/115284013/e20db793-7275-4ba5-981b-1ba4b3746f6c)

https://github.com/snehafarkya/Translate-Lingo/assets/115284013/2fb46f9f-2398-4c6a-8913-cc418404f026

(srry for bg noise :< )

**Comment by snehafarkya** [comment]
hey @Saumya40-codes , that's a great idea! You can work on this but before that tell me one thing, will it resume listening or it will start from the initial point?

**Comment by Saumya40-codes** [comment]
Currently it will start from initial point (i.e. completely stops it) but I can try for resume part to work

**Comment by snehafarkya** [comment]
okay @Saumya40-codes, you can work on this! Make sure to create a new branch. And, have you found any solution to resume it?

**Comment by Saumya40-codes** [comment]
@snehafarkya I wasn't able to find any solution for resuming the speech, looked into react-speech-kit repo for the same but couldn't found anything.
